In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df = pd.read_excel(r"C:\Users\Dell\OneDrive\Desktop\Full stack Data Science , Genai Agentic ai- NIT\python libraries\pandas\data.xlsx")

In [4]:
len(df)

195

In [5]:
df.shape

(195, 5)

In [6]:
df.isnull

<bound method DataFrame.isnull of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [7]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [8]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [9]:
df[:5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [10]:
df[5:10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [11]:
df[3:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [12]:
df[:35]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.90000,High income
1,Afghanistan,AFG,35.253,5.90000,Low income
2,Angola,AGO,45.985,19.10000,Upper middle income
3,Albania,ALB,12.877,57.20000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.00000,High income
5,Argentina,ARG,17.716,59.90000,High income
6,Armenia,ARM,13.308,41.90000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.40000,High income
8,Australia,AUS,13.200,83.00000,High income
9,Austria,AUT,9.400,80.61880,High income
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income
20,Belarus,BLR,12.500,54.17000,Upper middle income
21,Belize,BLZ,23.092,33.60000,Upper middle income
22,Bermuda,BMU,10.400,95.30000,High income
23,Bolivia,BOL,24.236,36.94000,Lower middle income
24,Brazil,BRA,14.931,51.04000,Upper middle income
25,Barbados,BRB,12.188,73.00000,High income
26,Brunei Darussalam,BRN,16.405,64.50000,High income
27,Bhutan,BTN,18.134,29.90000,Lower middle income
28,Botswana,BWA,25.267,15.00000,Upper middle income
29,Central African Republic,CAF,34.076,3.50000,Low income
30,Canada,CAN,10.900,85.80000,High income
31,Switzerland,CHE,10.200,86.34000,High income
32,Chile,CHL,13.385,66.50000,High income
33,China,CHN,12.100,45.80000,Upper middle income
34,Cote d'Ivoire,CIV,37.320,8.40000,Lower middle income

In [13]:
df[0:200:25]

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0         Aruba         ABW     10.244      78.900000          High income
25     Barbados         BRB     12.188      73.000000          High income
50      Ecuador         ECU     21.070      40.353684  Upper middle income
75     Honduras         HND     21.593      17.800000  Lower middle income
100       Libya         LBY     21.425      16.500000  Upper middle income
125     Namibia         NAM     29.937      13.900000  Upper middle income
150       Sudan         SDN     33.477      22.700000  Lower middle income
175     Tunisia         TUN     19.800      43.800000  Upper middle income

In [14]:
df[0:201:25]

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0         Aruba         ABW     10.244      78.900000          High income
25     Barbados         BRB     12.188      73.000000          High income
50      Ecuador         ECU     21.070      40.353684  Upper middle income
75     Honduras         HND     21.593      17.800000  Lower middle income
100       Libya         LBY     21.425      16.500000  Upper middle income
125     Namibia         NAM     29.937      13.900000  Upper middle income
150       Sudan         SDN     33.477      22.700000  Lower middle income
175     Tunisia         TUN     19.800      43.800000  Upper middle income

In [15]:
df[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [16]:
df[::-50]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
144,French Polynesia,PYF,16.393,56.8000,High income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
44,Czech Republic,CZE,10.200,74.1104,High income

In [17]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [18]:
df['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: object

In [19]:
df['CountryCode']

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: CountryCode, Length: 195, dtype: object

In [21]:
df[['BirthRate','InternetUsers']]

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [22]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [23]:
df_cat = df[['CountryName', 'CountryCode',
       'IncomeGroup']]
df_cat.head(1)

  CountryName CountryCode  IncomeGroup
0       Aruba         ABW  High income

In [24]:
df_num = df[['BirthRate','InternetUsers']]
df_num.head(1)

   BirthRate  InternetUsers
0     10.244           78.9

In [25]:
print(df.shape)
print(df_cat.shape)
print(df_num.shape)

(195, 5)
(195, 3)
(195, 2)

In [28]:
print(df.columns)
print(df_cat.columns)
print(df_num.columns)

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')
Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')
Index(['BirthRate', 'InternetUsers'], dtype='object')

In [29]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [30]:
df_cat.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [33]:
df['InternetUsers'] < 2

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

In [34]:
df[df['InternetUsers'] < 2] #fintering

      CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
11        Burundi         BDI     44.151            1.3           Low income
52        Eritrea         ERI     34.800            0.9           Low income
55       Ethiopia         ETH     32.925            1.9           Low income
64         Guinea         GIN     37.337            1.6           Low income
117       Myanmar         MMR     18.119            1.6  Lower middle income
127         Niger         NER     49.661            1.7           Low income
154  Sierra Leone         SLE     36.729            1.7           Low income
156       Somalia         SOM     43.891            1.5           Low income
172   Timor-Leste         TLS     35.755            1.1  Lower middle income

In [35]:
df['BirthRate']>40

0      False
1      False
2       True
3      False
4      False
       ...
190    False
191    False
192     True
193     True
194    False
Name: BirthRate, Length: 195, dtype: bool

In [38]:
df[df['BirthRate']>40]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
127,Niger,NER,49.661,1.7,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income

In [39]:
len(df[df['InternetUsers'] < 2]) #fintering

9

In [40]:
len(df[df['BirthRate']>40])

12

In [43]:
df[(df.BirthRate >40) & (df.InternetUsers < 2)]

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11      Burundi         BDI     44.151            1.3  Low income
127       Niger         NER     49.661            1.7  Low income
156     Somalia         SOM     43.891            1.5  Low income

In [45]:
df['IncomeGroup'] == 'High Income'

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: IncomeGroup, Length: 195, dtype: bool

In [46]:
df[df['IncomeGroup'] == 'High Income']

Empty DataFrame
Columns: [CountryName, CountryCode, BirthRate, InternetUsers, IncomeGroup]
Index: []

In [50]:
df['IncomeGroup'].unique()

array(['High income', 'Low income', 'Upper middle income',
       'Lower middle income'], dtype=object)

In [49]:
df['IncomeGroup'].nunique()

4

In [51]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [53]:
df.columns = ['a','b','c','d','e']

In [54]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [55]:
df.columns = ['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup']
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [61]:
df['myCalc'] = df.BirthRate * df.InternetUsers
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup,myCalc
0,Aruba,ABW,10.244,78.9,High income,808.2516
1,Afghanistan,AFG,35.253,5.9,Low income,207.9927
2,Angola,AGO,45.985,19.1,Upper middle income,878.3135
3,Albania,ALB,12.877,57.2,Upper middle income,736.5644
4,United Arab Emirates,ARE,11.044,88.0,High income,971.8720

In [62]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup', 'myCalc'],
      dtype='object')

In [63]:
df=df.drop('myCalc',axis =1)

In [64]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')